version: "3.8"
services:
  app:
    container_name: catalog-microservice
    build:
      context: ./
    ports:
      - 8080:80
    environment:
      - REDIS_HOST=catalog-redis
      - REDIS_PORT=6379
      - CACHE_TTL=3600
      - CONNECTION_STRING=mongodb://catalog-mongo:27017
    networks:
      - catalog-net  
  redis:
    image: redis:alpine
    container_name: catalog-redis
    ports:
        - 6379:6379
    networks:
      - catalog-net
  mongo:
    image: mongo
    container_name: catalog-mongo
    ports:
        - 27017:27017
    networks:
      - catalog-net         
networks:
  catalog-net:
    name: catalog-net
    driver: bridge      